[database]
user = "rm559582"
password = "Pato1234"
dsn = "oracle.fiap.com.br:1521/ORCL"

[mqtt]
server = "91c5f1ea0f494ccebe45208ea8ffceff.s1.eu.hivemq.cloud"
port = 8883
user = "FARM_TECH"
password = "Pato1234"